

let location = ["Amaravati", "Anantapur", "Chandragiri", "Chittoor", "Dowlaiswaram", "Eluru", "Guntur", "Kadapa", "Kakinada", "Kurnool", "Machilipatnam", "Nagarjunako", "Rajahmundry", "Srikakulam",
  "Tirupati", "Vijayawada", "Visakhapatnam", "Vizianagaram", "Yemmiganur", "Itanagar", "Dhuburi", "Dibrugarh", "Dispur", "Guwahati", "Jorhat", "Nagaon", "Sivasagar", "Silchar", "Tezpur", "Tinsukia", "Ara", "Barauni",
  "Begusarai", "Bettiah", "Bhagalpur", "Bihar Sharif", "Bodh Gaya", "Buxar", "Chapra", "Darbhanga", "Dehri", "Dinapur Nizamat", "Gaya", "Hajipur", "Jamalpur", "Katihar", "Madhubani", "Motihari", "Munger", "Muzaffarpur",
  "Patna", "Purnia", "Pusa", "Saharsa", "Samastipur", "Sasaram", "Sitamarhi", "Siwan", "Chandigarh", "Ambikapur", "Bhilai", "Bilaspur", "Dhamtari", "Durg", "Jagdalpur", "Raipur", "Rajnandgaon", "Daman", "Diu", "Silvassa",
  "Delhi", "New Delhi", "Madgaon", "Panaji", "Ahmadabad", "Amreli", "Bharuch", "Bhavnagar", "Bhuj", "Dwarka", "Gandhinagar", "Godhra", "Jamnagar", "Junagadh", "Kandla", "Khambhat", "Kheda", "Mahesana", "Morbi", "Nadiad",
  "Navsari", "Okha", "Palanpur", "Patan", "Porbandar", "Rajkot", "Surat", "Surendranagar", "Valsad", "Veraval", "Ambala", "Bhiwani", "Chandigarh", "Faridabad", "Firozpur", "Jhirka", "Gurugram", "Hansi", "Hisar",
  "Jind", "Kaithal", "Karnal", "Kurukshetra", "Panipat", "Pehowa", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Bilaspur", "Chamba", "Dalhousie", "Dharmshala", "Hamirpur", "Kangra", "Kullu", "Mandi", "Nahan", "Shimla", "Una",
  "Anantnag", "Baramula", "Doda", "Gulmarg", "Jammu", "Kathua", "Punch", "Rajouri", "Srinagar", "Udhampur", "Bokaro", "Chaibasa", "Deoghar", "Dhanbad", "Dumka", "Giridih", "Hazaribag", "Jamshedpur", "Jharia", "Rajmahal",
  "Ranchi", "Saraikela", "Badami", "Ballari", "Bengaluru", "Belagavi", "Bhadravati", "Bidar", "Chikkamagaluru", "Chitradurga", "Davangere", "Halebid", "Hassan", "Hubballi Dharwad", "Kalaburagi", "Kolar", "Madikeri",
  "Mandya", "Mangaluru", "Mysuru", "Raichur", "Shivamogga", "Shravanabelagola", "Shrirangapattana", "Tumakuru", "Vijayapura", "Alappuzha", "Vatakara", "Idukki", "Kannur", "Kochi", "Kollam", "Kottayam", "Kozhikode",
  "Mattancheri", "Palakkad", "Thalassery", "Thiruvananthapuram", "Thrissur", "Kargil", "Leh", "Balaghat", "Barwani", "Betul", "Bharhut", "Bhind", "Bhojpur", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh",
  "Datia", "Dewas", "Dhar", "Mhow", "Guna", "Gwalior", "Hoshangabad", "Indore", "Itarsi", "Jabalpur", "Jhabua", "Khajuraho", "Khandwa", "Khargone", "Maheshwar", "Mandla", "Mandsaur", "Morena", "Murwara", "Narsimhapur",
  "Narsinghgarh", "Narwar", "Neemuch", "Nowgong", "Orchha", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Sarangpur", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Ujjain", "Vidisha",
  "Ahmadnagar", "Akola", "Amravati", "Aurangabad", "Bhandara", "Bhusawal", "Bid", "Buldhana", "Chandrapur", "Daulatabad", "Dhule", "Jalgaon", "Kalyan", "Karli", "Kolhapur", "Mahabaleshwar", "Malegaon", "Matheran",
  "Mumbai", "Nagpur", "Nanded", "Nashik", "Osmanabad", "Pandharpur", "Parbhani", "Pune", "Ratnagiri", "Sangli", "Satara", "Sevagram", "Solapur", "Thane", "Ulhasnagar", "Vasai Virar", "Wardha", "Yavatmal", "Imphal",
  "Cherrapunji", "Shillong", "Aizawl", "Lunglei", "Kohima", "Mon", "Phek", "Wokha", "Zunheboto", "Balangir", "Baleshwar", "Baripada", "Bhubaneshwar", "Brahmapur", "Cuttack", "Dhenkanal", "Kendujhar", "Konark", "Koraput",
  "Paradip", "Phulabani", "Puri", "Sambalpur", "Udayagiri", "Karaikal", "Mahe", "Puducherry", "Yanam", "Amritsar", "Batala", "Chandigarh", "Faridkot", "Firozpur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala",
  "Ludhiana", "Nabha", "Patiala", "Rupnagar", "Sangrur", "Abu", "Ajmer", "Alwar", "Amer", "Barmer", "Beawar", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittaurgarh", "Churu", "Dhaulpur", "Dungarpur", "Ganganagar",
  "Hanumangarh", "Jaipur", "Jaisalmer", "Jalor", "Jhalawar", "Jhunjhunu", "Jodhpur", "Kishangarh", "Kota", "Merta", "Nagaur", "Nathdwara", "Pali", "Phalodi", "Pushkar", "Sawai Madhopur", "Shahpura", "Sikar", "Sirohi",
  "Tonk", "Udaipur", "Gangtok", "Gyalshing", "Lachung", "Mangan", "Arcot", "Chengalpattu", "Chennai", "Chidambaram", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kanchipuram", "Kanniyakumari",
  "Kodaikanal", "Kumbakonam", "Madurai", "Mamallapuram", "Nagappattinam", "Nagercoil", "Palayamkottai", "Pudukkottai", "Rajapalayam", "Ramanathapuram", "Salem", "Thanjavur", "Tiruchchirappalli", "Tirunelveli", "Tiruppur",
  "Thoothukudi", "Udhagamandalam", "Vellore", "Hyderabad", "Karimnagar", "Khammam", "Mahbubnagar", "Nizamabad", "Sangareddi", "Warangal", "Agartala", "Agra", "Aligarh", "Amroha", "Ayodhya", "Azamgarh", "Bahraich", "Ballia",
  "Banda", "Bara Banki", "Bareilly", "Basti", "Bijnor", "Bithur", "Budaun", "Bulandshahr", "Deoria", "Etah", "Etawah", "Faizabad", "Farrukhabad cum Fatehgarh", "Fatehpur", "Fatehpur Sikri", "Ghaziabad", "Ghazipur",
  "Gonda", "Gorakhpur", "Hamirpur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj", "Kanpur", "Lakhimpur", "Lalitpur", "Lucknow", "Mainpuri", "Mathura", "Meerut", "Mirzapur Vindhyachal", "Moradabad", "Muzaffarnagar",
  "Partapgarh", "Pilibhit", "Prayagraj", "Rae Bareli", "Rampur", "Saharanpur", "Sambhal", "Shahjahanpur", "Sitapur", "Sultanpur", "Tehri", "Varanasi", "Almora", "Dehra Dun", "Haridwar", "Mussoorie", "Nainital", "Pithoragarh",
  "Alipore", "Alipur Duar", "Asansol", "Baharampur", "Bally", "Balurghat", "Bankura", "Baranagar", "Barasat", "Barrackpore", "Basirhat", "Bhatpara", "Bishnupur", "Budge Budge", "Burdwan", "Chandernagore", "Darjeeling",
  "Diamond Harbour", "Dum Dum", "Durgapur", "Halisahar", "Haora", "Hugli", "Ingraj Bazar", "Jalpaiguri", "Kalimpong", "Kamarhati", "Kanchrapara", "Kharagpur", "Cooch Behar", "Kolkata", "Krishnanagar", "Malda", "Midnapore",
  "Murshidabad", "Nabadwip", "Palashi", "Panihati", "Purulia", "Raiganj", "Santipur", "Shantiniketan", "Shrirampur", "Siliguri", "Siuri", "Tamluk", "Titagarh"]


// let jobRoles = ["Software Engineer", "Frontend", "Backend", "Fullstack Developer", "Director of Ethical Hacking", "Data Analyst", "Blockchain", "Web Devloper", "Android Developer", "Devops Developer", "UI/UX Design", "Digital Marketing", "CRM Specialist", "Business Analyst", "Financial Analyst", "Marketing Manager", "Marketing Director", "Graphic Designer", "Marketing Research Analyst", "Marketing Communications Manager", "Marketing Consultant", -"Store Manager", "Account Executive",
//   "Account Manager", "Area Sales Manager", "Direct Salesperson", "Director of Inside Sales", "Outside Sales Manager", "Sales Analyst", "Market Development Manager", "B2B Sales Specialist", "Sales Engineer",
//   "Merchandising Associate", "CEO", "Proprietor", "Principal", "Owner", "President", "Founder", "Administrator", "Director", "Managing Partner", "Managing Member", "Board of Directors", "Shareholders", "Managers",
//   "Supervisors", "Front Line Employees", "Quality Control", "Human Resources", "Accounting Staff", "Marketing Staff", "Purchasing Staff", "Shipping and Receiving Staff", "Office Manager", "Receptionist", "Virtual Assistant",
//   "Customer Service", "Customer Support", "Concierge", "Help Desk", "Customer Service Manager", "Technical Support Specialist", "Account Representative", "Client Service Specialist", "Customer Care Associate", "Operations Manager",
//   "Operations Assistant", "Operations Coordinator", "Oper", "Operations Director", "Vice President of Operations", "Operations Professional", "Scrum Master", "Continuous Improvement Lead", "Continuous Improvement Consultant",
//   "Credit Authorizer", "Benefits Manager", "Credit Counselor", "Accountant", "Bookkeeper", "Accounting Analyst", "Accounting Director", "Accounts Payable Receivable Clerk", "Auditor", "Budget Analyst", "Controller",
//   "Financial Analyst", "Finance Manager", "Economist", "Payroll Manager", "Payroll Clerk", "Financial Planner", "Financial Services Representative", "Finance Director", "Commercial Loan Office", "Engineer", "Mechanical Engineer",
//   "Civil Engineer", "Electrical Engineer", "Assistant Engineer", "Chemical Engineer", "Chief Engineer", "Drafter", "Engineering Technician", "Geological Engineer", "Biological Engineer", "Maintenance Engineer", "Mining Engineer",
//   "Nuclear Engineer", "Petroleum Engineer", "Plant Engineer", "Production Engineer", "Quality Engineer", "Safety Engineer", "Sales Engineer", "Chief People Officer", "VP of Miscellaneous Stuff", "Chief Robot Whisperer",
//   "Director of First Impressions", "Culture Operations Manager", "Director of Bean Counting", "Digital Overlord", "Director of Storytelling", "Researcher",
//   "Research Assistant", "Biostatistician", "Title Researcher", "Market Researcher", "Title Analyst", "Medical Researcher", "Mentor", "Online Tutor", "Teacher",
//   "Teaching Assistant", "Substitute Teacher", "Preschool Teacher", "Test Scorer", "Online ESL Instructor", "Professor", "Assistant Professor"]


// let primarySkills = ["C", "Java", "Java Script", "Perl", "PHP", "Python", "Swift", "Go", "SQL", "R", "Ruby", "Google Suite", "Trello", "Slack", "Zapier", "Zoom", "JIRA", "Salesforce", "Budget planning", "Risk management",
//   "Project planning", "PM tools", "Task management", "SCRUM methodology", "Agile methodology", "Product roadmaps", "User experience design", "Programming skills", "Product lifecycle management", "QA testingng",
//   "Requirements gathering", "Coding", "Debugging", "Implementation", "Testing", "Design", "Configuration", "Applications", "Android", "Security", "Algorithms", "Modeling", "Documentation", "IOS", "Adobe creative ",
//   "HTML", "Interactive media", "Wireframing", "UX research", "Prototyping", "Color theory", "Responsive design", "Photoshop", "Sketch", "User modeling", "Search Engine Optimization ", "Digital media",
//   "Social media platforms", "Automated marketing software", "Content Management Systems ", "Copywriting",
//   "Content creation",
//   "Google Analytics",
//   "Marketing analytics tools",
//   "Accounting",
//   "Word processing",
//   "Spreadsheet building",
//   "Coding",
//   "Programming",
//   "Operating equipment",
//   "Engineering",
//   "Experimenting",
//   "Testing",
//   "Constructing",
//   "Restoring",
//   "Product developing",
//   "Quality controlling",
//   "Blueprint drafting",
//   "Repairing",
//   "Translating",
//   "Speaking",
//   "Writing",
//   "Conversing",
//   "Reinterpreting",
//   "Public speaking",
//   "Following etiquette",
//   "Explaining",
//   "Respecting",
//   "Signaling",
//   "Proofreading",
//   "Introducing",
//   "Representing",
//   "Rephrasing",
//   "Code switching",
//   "Graphic designing",
//   "Illustrating",
//   "Sketching",
//   "Architecture",
//   "User experience development",
//   "User interface development",
//   "Typography",
//   "Layout development",
//   "Web designing",
//   "Interior designing",
//   "Data visualizing",
//   "Hierarchical arranging",
//   "Aligning",
//   "Photo and video editing",
//   "Wireframing",
//   "Researching",
//   "Interpreting",
//   "Information processing",
//   "Organizing",
//   "Processing",
//   "Graphing",
//   "Computing",
//   "Calculating",
//   "Modeling",
//   "Extrapolating",
//   "Predicting",
//   "Forecasting",
//   "Investigating",
//   "Surveying",
//   "Statistical analysis"
// ];

let primarySkills = [
"3D printing",
"Abaqus",
"Adams",
"Adobe XD",
"Altair HyperWorks",
"Altium Designer ",
"Amazon Web Services (AWS)",
"Analog and Digital Electronics",
"Angular",
"ANSYS",
"Apache Kafka",
"ASP.NET",
"AutoCAD",
"Autodesk Inventor",
"AWS",
"Budgeting and Cost Estimation",
"Bug Tracking",
"C",
"C++",
"CAD",
"Cadence Allegro",
"CATIA",
"CATIA",
"CES Selector",
"CI CD",
"Circuit Design",
"Composite Material Simulation",
"Computational Fluid Dynamics",
"COMSOL Multiphysics",
"COMSOL",
"Control Systems",
"Creo",
"Critical Thinking",
"CSS",
"CST Studio Suite",
"Data Analysis and Interpretation",
"Data Cleaning",
"Data Modeling",
"Deep Learning",
"Design Optimization",
"Design Thinking",
"Digimat",
"Django",
"Docker",
"Eagle",
"Effective Presentation Skills",
"Electrical Circuit Analysis",
"Electromagnetic Simulation",
"Encryption",
"Engineering Codes and Standards",
"Engineering Documentation",
"Engineering Ethics",
"Environmental Impact Assessment",
"Excel",
"Experimental Design",
"Failure Analysis",
"FEA",
"Figma",
"Finite Element Analysis",
"Firewall Management",
"Flask",
"Fluent ",
"Fluid Mechanics",
"Flutter",
"formerly Unigraphics NX",
"Fusion 360",
"Git",
"Go",
"Google Cloud Platform",
"Hadoop",
"Hive",
"HTML",
"Ideation and Conceptualization",
"Incident Response",
"Injection Molding Simulation",
"Interdisciplinary Communication",
"ISO Standards",
"Java",
"JavaScript",
"Jenkins",
"JUnit",
"Kotlin",
"Kubernetes",
"LabVIEW",
"ladder logic",
"LAN WAN",
"Machine Learning",
"machining",
"Manual Testing",
"Material Selection",
"Materials Science and Properties",
"Mathematical Modeling and Analysis",
"MATLAB",
"Mentor Graphics PADS",
"Microcontrollers and Embedded Systems",
"Microsoft Azure",
"Microsoft SQL Server",
"Moldflow",
"MongoDB",
"Multibody Dynamics",
"MySQL",
"Network Security",
"Network Troubleshooting",
"NLP",
"Node.js",
"NoSQL Databases",
"Onshape",
"Oracle",
"OrCAD ",
"PCB Design",
"Penetration Testing",
"PHP",
"PLC",
"PostgreSQL",
"Power BI",
"Professional Development",
"Professional Responsibility",
"Programmable Logic Controller",
"Project Planning and Scheduling",
"Prototyping",
"Prototyping",
"Python",
"Python",
"Python",
"PyTorch",
"R",
"React Native",
"React",
"RecurDyn ",
"Regulatory Compliance",
"Renewable Energy Systems",
"Resource Management",
"Rhino 3D",
"Rhinoceros",
"Risk Assessment and Management",
"Risk Assessment and Mitigation",
"Root Cause Analysis",
"Routing and Switching",
"Ruby on Rails",
"Ruby",
"Security Information and Event Management",
"Selenium",
"Shell Scripting",
"Siemens NX",
"Simulink",
"Six Sigma",
"Sketch",
"SolidWorks",
"Spark",
"SQL",
"STAR CCM+",
"Statistical Analysis",
"Staying Updated with Latest Technologies and Trends",
"Structural Analysis and Design",
"Structural Analysis",
"Sustainable Design Practices",
"Swift",
"Systems Thinking",
"Tableau",
"TCP IP",
"Team Leadership and Management",
"Technical Report Writing",
"TensorFlow",
"Test Planning",
"Thermodynamics",
"TypeScript",
"User Research",
"VPN",
"Vue.js",
"welding",
"Wireframing",
"Working in Multidisciplinary Teams"]

let secondarySkills = [
  "Storytelling",
  "Written communication",
  "Editing",
  "Teaching",
  "Negotiating",
  "Open mindedness",
  "Inquiring",
  "Body language",
  "Customer service",
  "Presenting",
  "Summarizing",
  "Nonverbal communication",
  "Documenting",
  "Reporting",
  "Patience",
  "Positivity",
  "Conflict management",
  "Coaching",
  "Mediating",
  "Motivating",
  "Compassion",
  "Caring",
  "Networking",
  "Inspiring",
  "Flexibility",
  "Collaboration",
  "Sourcing feedback",
  "Reliability",
  "Empathy",
  "Observing",
  "Problem solving",
  "Inferring",
  "Simplifying",
  "Conceptual thinking",
  "Evaluating",
  "Streamlining",
  "Creative thinking",
  "Brainstorming",
  "Cost benefit analyzing",
  "Deductive reasoning",
  "Inductive reasoning",
  "Assessing",
  "Evidence collecting",
  "Troubleshooting",
  "Mentoring",
  "Envisioning",
  "Goal setting",
  "Employee development",
  "Performance reviewing",
  "Managing",
  "Planning",
  "Delegating",
  "Directing",
  "Supervising",
  "Training",
  "Earning trust",
  "Influencing",
  "Adapting",
  "Crisis managing"
];

let diffjobRole = [
   "Accounting Systems Analyst",
"Aeronautical Engineer",
"Air Quality ",
"Air Quality Engineer",
"Air Quality Manager",
"Air Quality Specialist",
"AIX Administrator",
"Analysis Engineer",
"Analytic Programmer",
"Android Developer",
"Application ",
"Application Analyst",
"Application Coordinator",
"Application Manager",
"Application Support Analyst",
"Application Support Manager",
"Applications Scientist",
"ASPNet Developer",
"Automation Application Engineer",
"Automation Engineer",
"Automation Engineering Manager",
"Automotive Engineer",
"Automotive Engineering ",
"Aviation Engineer",
"Avionics Engineer",
"Backend Developer",
"Backend Java Developer",
"Backup Administrator",
"Big Data Engineer",
"Bioengineer",
"Biomedical Engineer",
"Biomedical Engineering ",
"Biomedical Engineering Internship",
"Biomedical Manager",
"Bridge Engineer",
"Building Engineer",
"Business Analyst Intern",
"Business Analyst",
"Business Continuity ",
"Business Continuity Analyst",
"Business Continuity Manager",
"Business Intelligence ",
"Business Intelligence Analyst",
"Business Intelligence Developer",
"Business Intelligence Manager",
"Business Systems Analyst",
"Business Systems Manager",
"Cerner ",
"Cerner Analyst",
"Chemical Engineer",
"Chemical Engineering ",
"Chemical Engineering Intern",
"Chemical Process Engineer",
"Chief Analytics Officer",
"Chief Data Officer",
"Chief Engineer",
"Chief Informatics Officer",
"Chief Information Officer",
"Chief Information Security Officer",
"Chief Technical Officer",
"Chief Technologist",
"Chief Technology Officer",
"CISSP",
"Civil Engineer",
"Civil Engineering ",
"Civil Engineering Director",
"Civil Engineering Intern",
"Civil Engineering Manager",
"Civil Engineering Project Designer",
"Civil Engineering Project Manager",
"Civil Engineering Specialist",
"Civil Project Engineer",
"Civil Structural Engineer",
"Client Server Programmer",
"Clinical Application Manager",
"Clinical Engineer",
"Clinical Systems Analyst",
"CMS Expert",
"COBOL ",
"COBOL Programmer",
"Commissioning Engineer",
"Communications Engineer",
"Completions Engineer",
"Computer Engineering ",
"Computer Forensics ",
"Computer Forensics Analyst",
"Computer Hardware Engineer",
"Computer Information Systems ",
"Computer Networking Instructor",
"Computer Science Intern",
"Computer Scientist",
"Computer Support Specialist",
"Computer Technician",
"Configuration Manager",
"Construction Engineer",
"Construction Field Engineer",
"Consulting Engineer",
"Controls Engineer",
"Corrosion Engineer",
"CRM Consultant",
"Cryptographer",
"Cyber Security ",
"Data Analyst",
"Data Architect",
"Data Assistant",
"Data Center ",
"Data Center Manager",
"Data Collector",
"Data Coordinator",
"Data Management Engineer",
"Data Manager",
"Data Migration Lead",
"Data Operations Manager",
"Data Processing ",
"Data Processor",
"Data Reporting Analyst",
"Data Scientist",
"Data Steward",
"Data Warehouse ",
"Database Administrator",
"Database Analyst",
"Database Developer",
"DB2 DBA",
"DBA Manager",
"Decision Support Analyst",
"Decision Support Manager",
"Delivery Architect",
"Design Engineering ",
"Design Engineering Intern",
"Design Engineering Manager",
"Design Quality Engineer",
"Designer Writer",
"Development Engineer",
"DevOps Engineer",
"Digital Design Engineer",
"Digital Engineer",
"Digital Program Manager",
"Director Biomedical Engineering",
"Director Business Intelligence",
"Director Business Systems",
"Director Clinical Applications",
"Director Data Management",
"Director Data",
"Director Database",
"Director Decision Support",
"Director EHS",
"Director Electrical Engineering",
"Director Enterprise Systems",
"Director Game",
"Director Hardware",
"Director Information Security",
"Director Information",
"Director IT Project",
"Director IT",
"Director Manufacturing Engineering",
"Director of Engineering",
"Director of Mechanical Engineering",
"Director of User Experience",
"Director Oracle Database",
"Director Oracle",
"Director Software Development",
"Director Software Quality Assurance",
"Director Software",
"Director Systems",
"Director Telecommunications",
"Director Web",
"Distribution Designer",
"Domain Architect",
"Drainage Engineer",
"Drilling Engineer",
"Drilling Manager",
"Dynamitist",
"EHR Trainer",
"Electrical Controls Engineer",
"Electrical Electronics Engineer",
"Electrical Engineer",
"Electrical Engineering ",
"Electrical Engineering Designer",
"Electrical Engineering Intern",
"Electrical Engineering Manager",
"Electrical Project Engineer",
"Electrical Project Manager",
"Electrical Research Engineer",
"Electrical Systems Engineer",
"Electrical Test Engineer",
"Electro Mechanical Engineer",
"Electronic Engineering ",
"Electronics Engineer",
"Electronics Test Engineer",
"Embedded Engineer",
"Embedded Software ",
"Embedded Software Engineer",
"EMR Specialist",
"Energy Engineer",
"Energy Manager",
"Energy Systems Engineer",
"Engineering ",
"Engineering Analyst",
"Engineering Intern",
"Engineering Manager",
"Engineering Programmer",
"Engineering Project Designer",
"Engineering Project Designer",
"Engineering Project Manager",
"Engineering Project Manager",
"Engineering Systems Analyst",
"Enterprise Architect",
"Enterprise Data Architect",
"Enterprise Engineer",
"Enterprise Systems Manager",
"Environmental Engineer",
"Environmental Engineering ",
"Environmental Engineering Intern",
"Environmental Planner",
"Environmentalist",
"Epic Analyst",
"Epic Director",
"Epic Manager",
"Equipment Engineer",
"Ergonomist",
"Exchange Administrator",
"Exchange Consultant",
"Field Engineer",
"Financial Systems Administrator",
"Financial Systems Analyst",
"Firewall Engineer",
"Firmware Engineer",
"Firmware Manager",
"Flight Engineer",
"Flight Test Engineer",
"Foundation Engineer",
"Functional Analyst",
"Functional Tester",
"Game Designer",
"Game Master",
"Game Tester",
"General Engineer",
"Geological Engineer",
"Geospatial ",
"Geospatial Analyst",
"Geotechnical Engineer",
"GIS Administrator",
"GIS Analyst",
"GIS Coordinator",
"GIS Database Administrator",
"GIS Manager",
"GIS Scientist",
"Graphic Design Intern",
"Hadoop Developer",
"Hardware Design Engineer",
"Head Of Digital",
"Health Informatics ",
"Health Safety Engineer",
"Health Systems Analyst",
"Help Desk ",
"Help Desk Internship",
"Highway Engineer",
"Human Factors Engineer",
"Hydraulic Engineer",
"Hydrodynamicist",
"IC Design Engineer",
"ICT Analyst",
"Imaging Specialist",
"Implementation ",
"Implementation Coordinator",
"Implementation Director",
"Implementation Engineer",
"Implementation Manager",
"Implementation Specialist",
"Incident Manager",
"Incident Response Analyst",
"Industrial Design Intern",
"Industrial Engineer",
"Industrial Engineering Intern",
"Industrial Engineering Manager",
"Industrial Safety Engineer",
"Information Assurance ",
"Information Assurance Analyst",
"Information Assurance Engineer",
"Information Assurance Manager",
"Information Assurance Officer",
"Information Management Officer",
"Information Management Specialist",
"Information Security Analyst",
"Information Security Manager",
"Information Security Officer",
"Information Systems Coordinator",
"Information Systems Technician",
"Information Technology Professor",
"Integration Assistant",
"Integration Developer",
"Integration Director",
"Integration Engineer",
"Integration Manager",
"Integration Specialist",
"Intrusion Analyst",
"iOS Developer",
"IT Architecture Analyst",
"IT Auditor",
"IT Compliance Analyst",
"IT Compliance Manager",
"IT Manager",
"IT Program Engagement Director",
"IT Project Coordinator",
"IT Project Manager",
"IT Quality Analyst",
"IT Risk Analyst",
"IT Trainee",
"Java Developer",
"JavaScript ",
"JavaScript Developer",
"Knowledge Manager",
"Lab Engineer",
"Laser Engineer",
"Lean Manufacturing Engineer",
"Lighting Engineer",
"Linux System Administrator",
"Lotus Notes ",
"Lotus Notes Developer",
"Mainframe Developer",
"Mainframe Systems Engineer",
"Malware Analyst",
"Manager Android",
"Manager Hardware",
"Manager Java",
"Manager Linux",
"Manager Net",
"Manager PHP",
"Manager Telecom",
"Manager Unix",
"Manager Video Games",
"Manager Web Application",
"Manager Web",
"Manufacturing Controls Engineer",
"Manufacturing Engineer",
"Manufacturing Engineering ",
"Manufacturing Engineering Intern",
"Manufacturing Engineering Manager",
"Manufacturing Systems Engineer",
"Manufacturing Test Engineer",
"Marine Engineer",
"Master Data Analyst",
"Materials Engineer",
"Mechanical Design ",
"Mechanical Engineer",
"Mechanical Engineering ",
"Mechanical Engineering Intern",
"Mechanical Engineering Manager",
"Mechanical Engineering Specialist",
"Mechanical Engineering Technologist",
"Mechanical Inspector",
"Mechanical Intern",
"Mechanical Test Engineer",
"Medical Engineer",
"Metallographer",
"Metallurgical Engineer",
"Metallurgist",
"Metrologist",
"Microstrategy Architect",
"Mine Supervisor",
"Mining Engineer",
"Mobile Engineer",
"Mule Developer",
"Municipal Engineer",
"MySQL DBA",
"Naval Architect",
"Naval Engineer",
"Net Coordinator",
"Net Developer",
"Network Consultant",
"Network Controller",
"Network Coordinator",
"Network Designer",
"Network Developer",
"Network Director",
"Network Engineer",
"Network Internship",
"Network Management Specialist",
"Network Manager",
"Network Planner",
"Network Security ",
"Network Security Engineer",
"Network Systems Operator",
"Networking ",
"Networking Specialist",
"Nuclear Engineer",
"Object Oriented Programmer",
"Operations Engineer",
"Optical Engineer",
"Optimization Engineer",
"Oracle Database ",
"Oracle Database Analyst",
"Oracle Database Manager",
"Oracle DBA",
"Oracle Developer",
"Packaging Engineer",
"Penetration Tester",
"Peoplesoft ",
"Petroleum Engineer",
"PHP Developer",
"PL SQL Developer",
"Planning Engineer",
"Plastic Worker",
"Plastics Engineer",
"Platform Architect",
"Platform Engineer",
"Port Engineer",
"Portal Administrator",
"Portal Architect",
"Power Distribution Engineer",
"Printer Technician",
"Process Engineering Intern",
"Process Safety Engineer",
"Product Design ",
"Product Safety Engineer",
"Product Safety Manager",
"Program Architect",
"Program Engineer",
"Programming ",
"Project Development Engineer",
"Project Development Engineer",
"Project Engineer",
"Project Engineer",
"Project Engineering Manager",
"Project Engineering Manager",
"Project Management Engineer",
"Project Management Engineer",
"Propulsion Engineer",
"Quality Engineer",
"Registered Communications Distribution Designer",
"Release Coordinator",
"Release Engineer",
"Release Manager",
"Release Specialist",
"Reliability Engineer",
"Renewable Energy ",
"Renewable Energy Engineer",
"Renewable Energy Project Manager",
"Report Programmer",
"Reporting Analyst",
"Reporting Coordinator",
"Requirements Analyst",
"Requirements Manager",
"Research Chemical Engineer",
"Reservoir Engineer",
"Resident Engineer",
"Resident Inspector",
"RF Engineer",
"Robotics Engineer",
"Ruby on Rails Developer",
"Safety Engineer",
"Scientific Programmer",
"Scientist Engineer",
"Scrum Master",
"Security Administrator",
"Security Architect",
"Security Auditor",
"Security Developer",
"Security Engineer",
"Security Incident Response Engineer",
"Security Researcher",
"Semiconductor Engineer",
"Service Desk Associate",
"Service Desk Director",
"Service Desk Manager",
"SharePoint ",
"SharePoint Developer",
"SharePoint Manager",
"Siebel Administrator",
"Simulation Engineer",
"SOA Engineer",
"Software ",
"Software Configuration ",
"Software Development Coordinator",
"Software Development Manager",
"Software Engineer",
"Software Engineering ",
"Software Installer",
"Software Intern",
"Software Product Manager",
"Software QA Manager",
"Software Technician",
"Software Test Engineer",
"Software Test Technician",
"Software Testing ",
"Solar Energy Engineer",
"Solution Coordinator",
"Solution Director",
"Solution Manager",
"Solution Specialist",
"Solutions Architect",
"Solutions Engineer",
"SQL DBA",
"SQL Developer",
"SSRS Developer",
"Storage Consultant",
"Storage Engineer",
"Stress Engineer",
"Structural Designer",
"Structural Engineer",
"Supervisory IT Specialist",
"Supply Chain Engineer",
"System Safety Engineer",
"Systems Administrator",
"Systems Architect",
"Systems Coordinator",
"Systems Designer",
"Systems Engineer",
"Systems Integration Engineer",
"Systems Integration Manager",
"Systems Integrator",
"Systems Manager",
"Systems Specialist",
"Systems Test Analyst",
"Tech Intern",
"Tech Support ",
"Technical Analyst",
"Technical Assistant",
"Technical Consultant",
"Technical Director",
"Technical Manager",
"Technical Program Manager",
"Technical Service Engineer",
"Technical Service Representative",
"Technical Services Coordinator",
"Technical Specialist",
"Technical Support Manager",
"Technical Support Specialist",
"Technical Trainer",
"Technical Training ",
"Technical Training Coordinator",
"Technical Training Manager",
"Technology Adoption Manager",
"Technology Development Intern",
"Technology Officer",
"Technology Risk Intern",
"Telecom Assistant",
"Telecom Coordinator",
"Telecommunications ",
"Telecommunications Analyst",
"Telecommunications Specialist",
"Test Engineer",
"Test Engineering Intern",
"Threat Analyst",
"Tooling Engineer",
"Traffic Engineer",
"Transportation Engineer",
"Transportation Planning ",
"UAT Tester",
"Unix Administrator",
"User Experience Manager",
"User Experience Researcher",
"UX Designer",
"Verification Engineer",
"Vice President Network",
"Voice Engineer",
"VoIP Engineer",
"VP Data",
"VP Informatics",
"VP Information Technology",
"VP Integration",
"VP Software Engineering",
"VP Software Support",
"VP Software",
"Water Resources Engineer",
"Web Analyst",
"Web Developer",
"Web Development Intern",
"Web Operations Specialist",
"Webmaster",
"Wind Energy Engineer",
"Wind Turbine Electrical Engineer",
"Windows Administrator",
"Windows Software Engineer",
"Wireless Network Engineer",
"3D printing",
"Abaqus",
"Adams",
"Adobe XD",
"Altair HyperWorks",
"Altium Designer ",
"Amazon Web Services (AWS)",
"Analog and Digital Electronics",
"Angular",
"ANSYS",
"Apache Kafka",
"ASP.NET",
"AutoCAD",
"AutoCAD",
"Autodesk Inventor",
"AWS",
"Budgeting and Cost Estimation",
"Bug Tracking",
"C",
"C++",
"CAD",
"Cadence Allegro",
"CATIA",
"CATIA",
"CES Selector",
"CI CD",
"Circuit Design",
"Composite Material Simulation",
"Computational Fluid Dynamics",
"COMSOL Multiphysics",
"COMSOL",
"Control Systems",
"Creo",
"Critical Thinking",
"CSS",
"CST Studio Suite",
"Data Analysis and Interpretation",
"Data Cleaning",
"Data Modeling",
"Deep Learning",
"Design Optimization",
"Design Thinking",
"Digimat",
"Django",
"Docker",
"Eagle",
"Effective Presentation Skills",
"Electrical Circuit Analysis",
"Electromagnetic Simulation",
"Encryption",
"Engineering Codes and Standards",
"Engineering Documentation",
"Engineering Ethics",
"Environmental Impact Assessment",
"Excel",
"Experimental Design",
"Failure Analysis",
"FEA",
"Figma",
"Finite Element Analysis",
"Firewall Management",
"Flask",
"Fluent ",
"Fluid Mechanics",
"Flutter",
"formerly Unigraphics NX",
"Fusion 360",
"Git",
"Go",
"Google Cloud Platform",
"Hadoop",
"Hive",
"HTML",
"Ideation and Conceptualization",
"Incident Response",
"Injection Molding Simulation",
"Interdisciplinary Communication",
"ISO Standards",
"Java",
"JavaScript",
"Jenkins",
"JUnit",
"Kotlin",
"Kubernetes",
"LabVIEW",
"ladder logic",
"LAN WAN",
"Machine Learning",
"machining",
"Manual Testing",
"Material Selection",
"Materials Science and Properties",
"Mathematical Modeling and Analysis",
"MATLAB",
"Mentor Graphics PADS",
"Microcontrollers and Embedded Systems",
"Microsoft Azure",
"Microsoft SQL Server",
"Moldflow",
"MongoDB",
"Multibody Dynamics",
"MySQL",
"Network Security",
"Network Troubleshooting",
"NLP",
"Node.js",
"NoSQL Databases",
"Onshape",
"Oracle",
"OrCAD ",
"PCB Design",
"Penetration Testing",
"PHP",
"PLC",
"PostgreSQL",
"Power BI",
"Professional Development",
"Professional Responsibility",
"Programmable Logic Controller",
"Project Planning and Scheduling",
"Prototyping",
"Prototyping",
"Python",
"Python",
"Python",
"PyTorch",
"R",
"React Native",
"React",
"RecurDyn ",
"Regulatory Compliance",
"Renewable Energy Systems",
"Resource Management",
"Rhino 3D",
"Rhinoceros",
"Risk Assessment and Management",
"Risk Assessment and Mitigation",
"Root Cause Analysis",
"Routing and Switching",
"Ruby on Rails",
"Ruby",
"Security Information and Event Management",
"Selenium",
"Shell Scripting",
"Siemens NX",
"Simulink",
"Six Sigma",
"Sketch",
"SolidWorks",
"Spark",
"SQL",
"STAR CCM+",
"Statistical Analysis",
"Staying Updated with Latest Technologies and Trends",
"Structural Analysis and Design",
"Structural Analysis",
"Sustainable Design Practices",
"Swift",
"Systems Thinking",
"Tableau",
"TCP IP",
"Team Leadership and Management",
"Technical Report Writing",
"TensorFlow",
"Test Planning",
"Thermodynamics",
"TypeScript",
"User Research",
"VPN",
"Vue.js",
"welding",
"Wireframing",
"Working in Multidisciplinary Teams"]

let sectors = [
  "Fishing industry",
  "Horticulture industry",
  "Wood industry",
  "Mechanical Manufacturing",
  "Aerospace industry",
  "Automotive industry",
  "Chemical industry",
  "Pharmaceutical industry",
  "Construction industry",
  "Defense industry",
  "Arms industry",
  "Electric power industry",
  "Electronics industry",
  "Computer industry",
  "Semiconductor industry",
  "Energy industry",
  "Food industry",
  "Industrial robot industry",
  "Low technology industry",
  "Mining Industry",
  "Petroleum industry",
  "Oil shale",
  "Pulp and paper industry",
  "Steel industry",
  "Shipbuilding industry",
  "Telecommunications industry",
  "Textile industry",
  "Water industry",
  "Creative",
  "Advertising",
  "Fashion",
  "Floral",
  "Cultural industry",
  "Culture industry",
  "Education industry",
  "Entertainment industry",
  "Music industry",
  "Video game industry",
  "Financial services industry",
  "Insurance industry",
  "Healthcare industry",
  "Hospitality industry",
  "Information industry",
  "Leisure industry",
  "Mass media",
  "Broadcasting",
  "Internet",
  "News media",
  "Publishing",
  "Entertainment",
  "Professional services",
  "Real estate industry",
  "Retail industry",
  "Software industry",
  "Sport industry",
  "Transport industry"
];


let educationLevels = [
  'Master of Technology',
  'Master of Business Administration',
  'Bachelor of Technology',
  'Master Degree',
  'Bachelor Degree',
  'Diploma Equavalant to Bachelor degree',
  'Diploma Equavalant to Master degree',
  'Online Degree',
  'Advance Diploma',
  'PhD'
];

let experience = [

  { label: 'Fresher', value: 'Fresher' },
  { label: '1 Year', value: '1 Year' },
  { label: '2 Year', value: '2 Year' },
  { label: '3 Year', value: '3 Year' },
  { label: '4 Year', value: '4 Year' },
  { label: '5 Year', value: '5 Year' },
  { label: '6 Year', value: '6 Year' },
  { label: '7 Year', value: '7 Year' },
  { label: '8 Year', value: '8 Year' },
  { label: '9 Year', value: '9 Year' },
  { label: '10 Year', value: '10 Year' },
  { label: '11 Year', value: '11 Year' },
  { label: '11 to 15 Year', value: '11 to 15 Year' },
  { label: '15 to 20 Year', value: '15 to 20 Year' },
  { label: '20+ Year', value: '20+ Year' }

]

let experiences = [

  "Fresher",
  "1 Year",
  "2 Year",
  "3 Year",
  "4 Year",
  "5 Year",
  "6 Year",
  "7 Year",
  "8 Year",
  "9 Year",
  "10 Year",
  "11 to 15 Year",
  "15 to 20 Year",
  "20+ Year"
]


let yearofPassouts = [
  '2023', '2022', '2021', '2020' , "2019" , "2018","2017" ,"2016" ,
  "2015" ,"2014" ,"2013","2012" ,"2011" ,"2010"  ,"2009" ,"2008" ,
  "2007" ,"2006" ,"2005" ,"2004","2003","2002" ,"2001" ,"2000" ,
  "1999" ,"1998" ,"1997" ,"1996","1995","1994","1993" ,"1992" ,"1991" ,"1980"
]

let authorities = [
  'IIT',
  'IIM',
  'IISc',
  'NIT',
  'Central Govt',
  'State Govt',
  'Demeed University',
  'Private'
]

let experienceTypes = [

  'Job', 'Freelancer', 'Internship'
]

let jobNature = [
  "Full Time",
  "Part Time",
  "Work From Home" ,
  "Onsite",
  "Remote",
  "Hybrid",
  "Intership",
 

]


let companyTypes = [
  'MNC',
  'Start-Ups',
  'Government',
  'Service-Based',
  'Product-Based'
]

let jobCategory = [
  "Software Developer",
  "Software Management",
  "Software Quality",
  "System Administrator",
  "System Analyst",
  "Information Technology",
  "Business Intelligence",
  "Cyber Security",
  "Data Management",
  "Database Job",
  "Game Development",
  "Geographic IT",
  "Healthcare IT",
  "Help Desk Job",
  "Information Technology Intern",
  "IT Audit",
  "IT Coordinator",
  "IT Executive Job",
  "IT Management",
  "IT Project",
  "IT Specialist",
  "IT Training",
  "Network",
  "Engineering",
  "Automotive Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Construction Engineers",
  "Design Engineering",
  "Electrical Engineering",
  "Energy Engineers",
  "Environmental Engineering",
  "Industrial Engineering",
  "Manufacturing Engineering",
  "Materials Engineering",
  "Mechanical Engineering",
  "Petroleum Engineering",
  "Project Engineering",
  "Safety Engineers",
  "Engineering Intern"
];

let states = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Lakshadweep',
  'Puducherry'
]

let disciplines = [
  "Computer science",
  "Computing in social sciences",
  "Chemical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Educational Technology",
  "Materials Science and Engineering",
  "Mechanical Engineering",
  "Systems science",
  "Mathematics",
  "Agriculture",
  "Astronomy",
  "Physics",
  "Earth science",
  "Chemistry",
  "Biology",
  "Philosophy",
  "Law",
  "Languages and literature",
  "History",
  "Visual arts",
  "Environmental studies and forestry",
  "Languages and literatureHistory",
  "Architecture and design",
  "Agriculture",
  "Anthropology",
  "Archaeology",
  "Economics",
  "Linguistics",
  "Political science",
  "Social work",
  "Sociology",
  "Psychology",
  "Physical geography",
  "Human geography",
  "Cartography"
]

let jobRoles = {
  "Software Developer": [
    "Web Developer",
    "Java Developer",
    "UX Designer",
    "Net Developer",
    "iOS Developer",
    "Android Developer",
    "SharePoint Developer",
    "DevOps Engineer",
    "Solutions Engineer",
    "Ruby on Rails Developer",
    "PHP Developer",
    "Integration Engineer",
    "Release Engineer",
    "Embedded Software Engineer",
    "Oracle Developer",
    "Computer Scientist",
    "JavaScript Developer",
    "Web Analyst",
    "Mainframe Developer",
    "Platform Engineer",
    "User Experience Researcher",
    "Backend Developer",
    "Systems Integration Engineer",
    "Integration Developer",
    "Applications Scientist",
    "COBOL Programmer",
    "Enterprise Engineer",
    "Scientific Programmer",
    "Lotus Notes Developer",
    "Software Technician",
    "Security Developer",
    "Backend Java Developer",
    "Release Specialist",
    "Automation Application Engineer",
    "Object Oriented Programmer",
    "Windows Software Engineer",
    "Client Server Programmer",
    "Engineering Programmer",
    "Analytic Programmer",
    "ASPNet Developer",
    "IT Architecture Analyst",
    "Mule Developer",
    "Report Programmer",
    "SOA Engineer",
    "Software Jobs",
    "Oracle Jobs",
    "Java Jobs",
    "UX Jobs",
    "Software Engineering Jobs",
    "Application Jobs",
    "Rails Jobs",
    "Reporting Jobs",
    "Peoplesoft Jobs",
    "JavaScript Jobs",
    "SharePoint Jobs",
    "Programming Jobs",
    "DevOps Jobs",
    "PHP Jobs",
    "Embedded Software Jobs",
    "COBOL Jobs",
    "Software Configuration Jobs",
    "Lotus Notes Jobs"
  ],
  "Software Management": [
    "Solutions Architect",
    "Data Architect",
    "Application Manager",
    "Enterprise Architect",
    "Systems Architect",
    "Scrum Master",
    "Software Development Manager",
    "Solution Director",
    "Director Software Development",
    "Director Software",
    "Manager Web",
    "Director Systems",
    "Director of User Experience",
    "User Experience Manager",
    "Director Web",
    "Software Product Manager",
    "Enterprise Data Architect",
    "Platform Architect",
    "Delivery Architect",
    "Application Support Manager",
    "Domain Architect",
    "Manager Java",
    "Enterprise Systems Manager",
    "Portal Architect",
    "Program Architect",
    "Director Enterprise Systems",
    "Head Of Digital",
    "Manager Web Application",
    "Scrum Master"
  ],
  "System Analyst": [
    "Business Analyst",
    "Business Systems Analyst",
    "Solution Specialist",
    "Application Analyst",
    "Technical Specialist",
    "Application Support Analyst",
    "Functional Analyst",
    "Requirements Analyst",
    "Financial Systems Analyst",
    "Engineering Systems Analyst",
    "Accounting Systems Analyst"
  ],
  "Software Quality": [
    "Software Test Engineer",
    "Software QA Manager",
    "Functional Tester",
    "UAT Tester",
    "Director Software Quality Assurance",
    "Systems Test Analyst",
    "Software Test Technician"
  ],
  "System Administrator": [
    "Systems Engineer",
    "Systems Administrator",
    "Systems Specialist",
    "Webmaster",
    "Linux System Administrator",
    "Systems Manager",
    "Windows Administrator",
    "Unix Administrator",
    "Storage Engineer",
    "Systems Designer",
    "Exchange Administrator",
    "Business Systems Manager",
    "Backup Administrator",
    "Storage Consultant",
    "AIX Administrator",
    "Financial Systems Administrator",
    "Manager Android",
    "Mainframe Systems Engineer",
    "Siebel Administrator",
    "Linux Jobs",
    "Unix Jobs"
  ],
    "Business Intelligence": [
        "Business Intelligence Developer",
        "Data Scientist",
        "Business Intelligence Analyst",
        "Big Data Engineer",
        "Business Intelligence Manager",
        "Hadoop Developer",
        "Decision Support Analyst",
        "Director Business Intelligence",
        "Master Data Analyst",
        "Decision Support Manager",
        "Microstrategy Architect",
        "Director Decision Support",
        "Big Data",
        "Analytics",
        "Hadoop"
    ],
    
  'IT Audit': [
    "IT Auditor",
    "IT Risk Analyst",
    "IT Compliance Analyst",
    "Security Auditor",
    "IT Compliance Manager",

  ],
  'IT Executive Job': [
    "Chief Information Officer (CIO)",
    "Chief Technology Officer (CTO)",
    "VP Information Technology",
    "Chief Information Security Officer",
    "VP Software Engineering",
    "VP Software",
    "Chief Technologist",
    "Vice President Network",
    "Chief Technical Officer",
    "Chief Data Officer",
    "VP Data",
    "Chief Analytics Officer",
    "Chief Informatics Officer",
    "VP Informatics",
    "VP Integration",
    "VP Software Support",

  ],
  'Engineering': [
    "Quality Engineer",
    "Field Engineer",
    "Test Engineer",
    "Development Engineer",
    "Engineering Manager",
    "Controls Engineer",
    "Operations Engineer",
    "Automation Engineer",
    "Aeronautical Engineer",
    "Reliability Engineer",
    "Configuration Manager",
    "Packaging Engineer",
    "Chief Engineer",
    "Director of Engineering",
    "RF Engineer",
    "Consulting Engineer",
    "Building Engineer",
    "Geotechnical Engineer",
    "Resident Engineer",
    "Metallurgist",
    "Verification Engineer",
    "Scientist Engineer",
    "Transportation Engineer",
    "Tooling Engineer",
    "Analysis Engineer",
    "Optimization Engineer",
    "Drilling Engineer",
    "Traffic Engineer",
    "Optical Engineer",
    "Equipment Engineer",
    "Marine Engineer",
    "Commissioning Engineer",
    "Completions Engineer",
    "Robotics Engineer",
    "General Engineer",
    "Planning Engineer",
    "Flight Test Engineer",
    "Implementation Engineer",
    "Simulation Engineer",
    "Mining Engineer",
    "Hardware Design Engineer",
    "Metrologist",
    "Supply Chain Engineer",
    "Voice Engineer",
    "Human Factors Engineer",
    "Municipal Engineer",
    "Engineering Analyst",
    "Embedded Engineer",
    "Mobile Engineer",
    "Distribution Designer",
    "Flight Engineer",
    "Plastics Engineer",
    "Metallurgical Engineer",
    "Propulsion Engineer",
    "Naval Architect",
    "Program Engineer",
    "Lab Engineer",
    "Corrosion Engineer",
    "Avionics Engineer",
    "Drainage Engineer",
    "Aviation Engineer",
    "Drilling Manager",
    "Bioengineer",
    "Ergonomist",
    "Hydraulic Engineer",
    "Port Engineer",
    "Lighting Engineer",
    "Geological Engineer",
    "Laser Engineer",
    "Mine Supervisor",
    "Dynamicist",
    "Registered Communications Distribution Designer",
    "Semiconductor Engineer",
    "Metallographer",
    "Resident Inspector",
    "Foundation Engineer",
    "Hydrodynamicist",
    "Naval Engineer",
    "Plastic Worker",
    "Engineering Jobs",
    "Robotics Jobs",
    "Computer Engineering Jobs",
    "Transportation Planning Jobs",

  ],
  'Automotive Engineering' :[
    "Automotive Engineer",
"Automation Engineering Manager",
"Automotive Engineering Jobs",

  ]  , 
  "Biomedical Engineering" : [
    "Biomedical Engineer",
"Clinical Engineer",
"Medical Engineer",
"Director Biomedical Engineering",
"Biomedical Manager",
"Biomedical Engineering Jobs",

  ] , 
   "Chemical Engineering "  : [
    "Chemical Engineer",
"Chemical Process Engineer",
"Research Chemical Engineer",
"Chemical Engineering Jobs",
 
   ] , 
   'Civil Engineering' : [
    "Civil Engineer",
"Structural Engineer",
"Bridge Engineer",
"Structural Designer",
"Civil Structural Engineer",
"Highway Engineer",
"Stress Engineer",
"Civil Project Engineer",
"Civil Engineering Manager",
"Civil Engineering Project Manager",
"Civil Engineering Director",
"Civil Engineering Specialist",
"Civil Engineering Project Designer",
"Civil Engineering Jobs",

   ] , 
   "Design Engineering" : [
    "IC Design Engineer",
"Digital Design Engineer",
"Digital Engineer",
"Design Engineering Manager",
"Design Quality Engineer",
"Product Design Jobs",
"Design Engineering Jobs",

   ] ,
   'Construction Engineers' :[
    "Construction Engineer",
"Construction Field Engineer",

   ]  ,
   'Manuracturing Engineering' :[
    "Manufacturing Engineer",
"Manufacturing Engineering Manager",
"Manufacturing Test Engineer",
"Lean Manufacturing Engineer",
"Director Manufacturing Engineering",
"Manufacturing Controls Engineer",
"Manufacturing Systems Engineer",
"Manufacturing Engineering Jobs",

   ] ,
   'Environmental Engineering':[
    "Environmental Engineer",
"Water Resources Engineer",
"Reservoir Engineer",
"Environmental Planner",
"Environmentalist",
"Air Quality Specialist",
"Air Quality Engineer",
"Air Quality Manager",
"Environmental Engineering Jobs",
"Air Quality Jobs",


   ]  ,
'Energy Engineers': [
  "Energy Manager",
"Nuclear Engineer",
"Energy Engineer",
"Renewable Energy Engineer",
"Energy Systems Engineer",
"Power Distribution Engineer",
"Solar Energy Engineer",
"Renewable Energy Project Manager",
"Wind Turbine Electrical Engineer",
"Wind Energy Engineer",
"Renewable Energy Jobs",
"Wind Energy Jobs",

] ,
'Industrial Engineering' :[
  "Industrial Engineer",
"Industrial Engineering Manager",

]  ,
'Engineering Intern' :[
  "Engineering Intern",
"Mechanical Engineering Intern",
"Electrical Engineering Intern",
"Manufacturing Engineering Intern",
"Industrial Engineering Intern",
"Environmental Engineering Intern",
"Chemical Engineering Intern",
"Civil Engineering Intern",
"Biomedical Engineering Internship",
"Industrial Design Intern",
"Process Engineering Intern",
"Design Engineering Intern",
"Mechanical Intern",
"Test Engineering Intern",

] , 
'Safety Engineers':[
  "Safety Engineer",
"Director EHS",
"Process Safety Engineer",
"System Safety Engineer",
"Health Safety Engineer",
"Product Safety Engineer",
"Product Safety Manager",
"Industrial Safety Engineer",

] ,
'Project Engineering' : [
  "Project Engineer",
"Engineering Project Manager",
"Project Engineering Manager",
"Project Development Engineer",
"Project Management Engineer",
"Engineering Project Designer",


] ,
'Petroleum Engineering': ["Petroleum Engineer",] ,
'Mechanical Engineering' : ["Mechanical Engineer",
"Mechanical Inspector",
"Mechanical Engineering Manager",
"Electro Mechanical Engineer",
"Mechanical Test Engineer",
"Director of Mechanical Engineering",
"Mechanical Engineering Specialist",
"Mechanical Engineering Technologist",
"Mechanical Engineering Jobs",
"Mechanical Design Jobs",
]  ,
'Materials Engineering' : [
  "Materials Engineer",

] ,
'Electrical Engineering' : [
  "Electrical Engineer",
"Electronics Engineer",
"Electrical Controls Engineer",
"Electrical Project Manager",
"Electrical Project Engineer",
"Electrical Systems Engineer",
"Electrical Engineering Manager",
"Electrical Test Engineer",
"Electronics Test Engineer",
"Electrical Electronics Engineer",
"Electrical Engineering Designer",
"Director Electrical Engineering",
"Electrical Research Engineer",
"Electrical Engineering Jobs",
"Electronic Engineering Jobs",

]





};

let salary = [
  "1 Lpa" ,
  "2 Lpa",
  "3 Lpa",
  "4 Lpa",
  "5 Lpa",
  "6 Lpa",
  "7 Lpa",
  "8 Lpa", 
  "9 Lpa", 
  "10 Lpa",
   "More than 10 Lpa"]   ;


  let projectsType = [
    "Research Project" ,
    "College Project" ,
    "Entrprenuer Project" , 
    "Personal Project"    
    ]      

export {
  jobNature,
  location,
  jobRoles,
  primarySkills,
  secondarySkills,
  diffjobRole,
  sectors,
  educationLevels,
  experience,
  yearofPassouts,
  authorities,
  experienceTypes,
  companyTypes,
  experiences,
  jobCategory,
  disciplines,
  salary,
  projectsType,
  states
}